/*
 * generated by Xtext 2.21.0
 */
package org.agileware.natural.words.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.agileware.natural.words.WordsRuntimeModule;
import org.agileware.natural.words.WordsStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class WordsIdeSetup extends WordsStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new WordsRuntimeModule(), new WordsIdeModule()));
	}
	
}
