/*
 * generated by Xtext 2.21.0
 */
package org.agileware.natural.words.tests

import com.google.inject.Inject
import org.agileware.natural.words.words.WordsModel
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith

import static org.hamcrest.CoreMatchers.*
import static org.hamcrest.MatcherAssert.*

@ExtendWith(InjectionExtension)
@InjectWith(WordsInjectorProvider)
class WordsParsingTest {

	@Inject
	ParseHelper<WordsModel> parseHelper

	@Test
	def void singleParagraph() {
		val model = parseHelper.parse('''
			The quick brown fox
			Jumps over the lazy dog
		''')
	
		assertThat(model, notNullValue())
		assertThat(model.eResource.errors, equalTo(#[]))
		
		val doc = model.document
		assertThat(doc, notNullValue())
		assertThat(doc.sections.size(), equalTo(1))
		assertThat(doc.sections.get(0).lines.size(), equalTo(2))
		// It works!
	}
	
	@Test
	def void multiParagraph() {
		val model = parseHelper.parse('''
			The quick brown fox
			Jumps over the lazy dog
			
			But only on days that end in Y
		''')
	
		assertThat(model, notNullValue())
		assertThat(model.eResource.errors, equalTo(#[]))
		
		val doc = model.document
		assertThat(doc, notNullValue())
		assertThat(doc.sections.size(), equalTo(2))
		assertThat(doc.sections.get(0).lines.size(), equalTo(2))
	}
}
