/*
 * generated by Xtext 2.21.0
 */
package org.agileware.natural.words.tests

import com.google.inject.Inject
import org.agileware.natural.words.tracer.WordsTracer
import org.agileware.natural.words.words.WordsModel
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith

import static org.hamcrest.CoreMatchers.*
import static org.hamcrest.MatcherAssert.*

@ExtendWith(InjectionExtension)
@InjectWith(WordsInjectorProvider)
class WordsParsingTest {
	@Inject
	ParseHelper<WordsModel> parseHelper
	
	@Inject
	extension WordsTracer
	
	@Test
	def void loadModel() {
		val model = parseHelper.parse('''
			Hello Xtext
		''')
		assertThat(model, notNullValue())
		model.trace()
		
		assertThat(model.eResource.errors, equalTo(#[]))
	}
}
