/*
 * generated by Xtext 2.21.0
 */
package org.agileware.natural.words.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class WordsUiModule extends AbstractWordsUiModule {

	public WordsUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
